# Project information
site_name: "Octallium"
site_description: "Tech In Evolution"
site_author: "Anil Kulkarni"
site_url: "https://www.octallium.com"

# Copyright
copyright: "Copyright &copy; 2022, Octallium Inc."

theme:
  name: "material"
  language: "en"
  logo: "assets/images/brand/octallium-header-logo-black.png"
  favicon: "assets/images/brand/octallium-header-logo-black.png"
  font:
    text: "IBM Plex Sans"
    code: "Roboto Mono"
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
  palette:
    primary: "white"
    accent: "indigo"


extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: "https://www.github.com/octallium"
    - icon: fontawesome/brands/youtube
      link: "https://www.youtube.com/channel/UCdjL6fiMCepdcuVg2qhdABA"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/octallium"
    - icon: fontawesome/brands/facebook
      link: "https://www.facebook.com/octallium"
    - icon: fontawesome/brands/instagram
      link: "https://www.instagram.com/octallium"

# Google Analytics
google_analytics:
  - "UA-121309781-3"
  - "auto"

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Nav
nav:
  - Home: "index.md"
  - About:
      "about.md"
      # - "About Me": "about/about-me.md"
      # - "Contributing Content": "about/contribution.md"
  # - Donate:
  #     - Donate: "donate.md"
  - Courses:
    - "Modern Python 101 - Workouts": "courses/modern-python-101-workouts.md"
    - "Modern Python 101": "courses/modern-python-101.md"
  - Tutorials:
    - Python:
        - Basics:
            - Introduction: "tutorials/python/basics/introduction.md"
            - Installation: "tutorials/python/basics/installation.md"
            - Variables: "tutorials/python/basics/variables.md"
            - "Data Types": "tutorials/python/basics/data-types.md"
            - Functions: "tutorials/python/basics/functions.md"
            - "If Else": "tutorials/python/basics/if-else.md"
            - "Static Typing": "tutorials/python/basics/static-typing.md"
            - List: "tutorials/python/basics/list.md"
            - Loops: "tutorials/python/basics/loops.md"
            - Strings: "tutorials/python/basics/strings.md"
            - Dictionary: "tutorials/python/basics/dictionary.md"
            - Tuple: "tutorials/python/basics/tuple.md"
            - Set: "tutorials/python/basics/set.md"
            - Packages: "tutorials/python/basics/packages.md"
            - "Object Oriented Programming": "tutorials/python/basics/oop.md"
            - "File Handling": "tutorials/python/basics/file-handling.md"
            - "Error Handling": "tutorials/python/basics/error-handling.md"
        # - Intermediate:
        #     - "List Comprehensions": "tutorials/python/intermediate/list-comprehensions.md"
        #     - Lambda: "tutorials/python/intermediate/lambda.md"
        #     - "Magic Methods": "tutorials/python/intermediate/magic-methods.md"
        #     - "ABC Class": "tutorials/python/intermediate/abc-class.md"
        #     - "Multi Threading": "tutorials/python/intermediate/multi-threading.md"
        #     - "Async Await": "tutorials/python/intermediate/async-await.md"
        #     - "Generators and Iterators": "tutorials/python/intermediate/generators-iterators.md"
        #     - Testing: "tutorials/python/intermediate/testing.md"
        #     - "Named Tuple": "tutorials/python/intermediate/named-tuple.md"
        #     - "Functional Programming": "tutorials/python/intermediate/functional-programming.md"
        #     - "Command Line Applications": "tutorials/python/intermediate/cli.md"
        #     - "Regular Expressions": "tutorials/python/intermediate/regular-expression.md"
        #     - Database: "tutorials/python/intermediate/database.md"
        #     - Logging: "tutorials/python/intermediate/logging.md"
        #     - "Introduction to HTTP": "tutorials/python/intermediate/intro-http.md"

    - Elixir:
        - Basics:
            - Introduction: "tutorials/elixir/basics/introduction.md"
            - Installation: "tutorials/elixir/basics/installation.md"
            - IEx: "tutorials/elixir/basics/iex.md"
            - "Hello Elixir": "tutorials/elixir/basics/hello_elixir.md"
            - "Data Types": "tutorials/elixir/basics/data-types.md"
            - "Basic Operations": "tutorials/elixir/basics/basic-operations.md"
            - "Modules and Functions": "tutorials/elixir/basics/modules-functions.md"
            - "Pipe Operator": "tutorials/elixir/basics/pipe.md"
            - "Pattern Matching": "tutorials/elixir/basics/pattern-matching.md"
            - Mix: "tutorials/elixir/basics/mix.md"
            - Strings: "tutorials/elixir/basics/strings.md"
            - Sigils: "tutorials/elixir/basics/sigil.md"
            - Lists: "tutorials/elixir/basics/lists.md"
            - Map: "tutorials/elixir/basics/map.md"
            - List: "tutorials/elixir/basics/lists.md"
            - Enumerable: "tutorials/elixir/basics/enum.md"
            - Iterable: "tutorials/elixir/basics/iterable.md"
            - "Case, Cond and If": "tutorials/elixir/basics/case-cond-if.md"
            - Streams: "tutorials/elixir/basics/stream.md"
            - Comprehensions: "tutorials/elixir/basics/comprehensions.md"
            - Struct: "tutorials/elixir/basics/struct.md"
            - Doctest: "tutorials/elixir/basics/doctest.md"
            - "File Handling": "tutorials/elixir/basics/file-handling.md"
            - "Alias, Require and Import": "tutorials/elixir/basics/alias-require-import.md"
            - "Erlang Libraries": "tutorials/elixir/basics/erlang-lib.md"
            - Testing: "tutorials/elixir/basics/testing.md"
            - Processes: "tutorials/elixir/basics/processes.md"
            - Spawn: "tutorials/elixir/basics/spawn.md"

  # - Go:
  #     - Getting Started:
  #         - "Why Go": "go/getting-started/why-go.md"
  #         - "Installation": "go/getting-started/installation.md"
  #         - "Editors and IDE": "go/getting-started/editor_ide.md"
  #     - Basics:
  #         - Introduction: "go/basics/introduction.md"
  #         - "01 Hello World": "go/basics/hello-world.md"
  #         - "02 Understanding Hello World": "go/basics/hello-world-understand.md"
  #         - "03 Adding a Comment": "go/basics/add-comment.md"
  #         - "04 Understanding Data Types": "go/basics/basic-data-types.md"
  #         - "05 Variables & Constants": "go/basics/variables-constants.md"
  #         - "06 Shorthand Declaration": "go/basics/shorthand-declaration.md"
  #         - "07 Condition - if/else": "go/basics/if-else.md"
  #         - "08 For Loops": "go/basics/for_loops.md"
  #         - "09 Function": "go/basics/functions.md"
  #         - "10 Packages": "go/basics/packages.md"
  #         - "11 Array": "go/basics/array.md"
  #         - "12 Slice": "go/basics/slice.md"
  #         - "13 Map": "go/basics/map.md"

  - Subscribe:
      - Subscribe: "subscribe.md"
  # - Contact:
  #     - Connect: "contact/contact.md"
